### ISSUE TITLE
Docs: what is the scope of functions?

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#1160]
For instance, if I have something like this:

```tact
fun foo() { ... }
fun bar() { ... }
```

`bar` should be able to refer to `foo`, but can `foo` call `bar`?

**Comment by novusnota** [comment]
Can't test in Nujan — doing the following throws `RangeError: Maximum call stack size exceeded` in Next.js bundled chunks (line:column positions there don't tell anything about the original sources):

```tact
import "@stdlib/deploy";

fun foo(a: Int): Int {
    if (a <= 1) { return 1; }
    return bar(a - 1);
}

fun bar(b: Int): Int {
    if (b <= 1 ) { return 1; }
    return foo(b - 1);
}

contract Example with Deployable {
   init() {} // because there's Tact 1.2.0
   get fun call(): Int {
       return foo(10) + bar(10); // should return 2, but doesn't build in Nujan
   }
}
```

Meanwhile, the following re-write in TypeScript works and produces 2, as it should:

```typescript
function foo(a: number): number {
    if (a <= 1) { return 1; }
    return bar(a - 1);
}

function bar(b: number): number {
    if (b <= 1 ) { return 1; }
    return foo(b - 1);
}

console.log(foo(10) + bar(10));
```

I'll investigate this matter locally with Blueprint later on. If that works, I'll file an issue to Nujan

**Comment by novusnota** [comment]
Just tested locally with latest Tact on main branch — the RangeError is thrown by us. Specifically, if one tries to compile the snippet above (https://github.com/tact-lang/tact/issues/1160), the following error is thrown:

```shell
Tact compilation failed
RangeError: Maximum call stack size exceeded
    at Set.values (<anonymous>)
    at visit (/tact/dist/generator/Writer.js:69:35)
    at visit (/tact/dist/generator/Writer.js:70:21)
    at visit (/tact/dist/generator/Writer.js:70:21)
    at visit (/tact/dist/generator/Writer.js:70:21)
    at visit (/tact/dist/generator/Writer.js:70:21)
    at visit (/tact/dist/generator/Writer.js:70:21)
    at visit (/tact/dist/generator/Writer.js:70:21)
    at visit (/tact/dist/generator/Writer.js:70:21)
    at visit (/tact/dist/generator/Writer.js:70:21)
```

Compilation fails even with `foo(1) + bar(1)`, which should give 2 almost immediately

**Comment by anton-trunov** [comment]
I believe there is a bug somewhere in the writer, but even if fixed this won't be possible right now: all the functions are topologically sorted before code generation. Removing toposort changes gas consumption of the generated contracts (I assume FunC does something interesting there)

**Comment by anton-trunov** [comment]
And toposorting mutually recursive functions is impossible because of the dependency loop, of course. Me might want to try using Tarjan's SCC algorithm here to try and overcome the gas issue

**Comment by novusnota** [comment]
Done in #3076
