### ISSUE TITLE
Add Node.js 23 to CI

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#1217]
```shell
$ yarn
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error release-it@17.10.0: The engine "node" is incompatible with this module. Expected version "^18.18.0  ^20.9.0  ^22.0.0". Got "23.1.0"
error Found incompatible module.
```

Reported by @Shvandre: he mentions it used to work until recently

**Comment by Shvandre** [comment]
And also 
> in newer versions of Node.js our grammar.ts has to be updated with ['astOfSmth' ] accesses and not .astOfSmth()

Or it will cause an error like this
```
$ tact --config ./tact.config.json
/home/b4cksl4sh/tact/node_modules/ohm-js/dist/ohm.cjs:4484
      throw error;
      ^

Error: Found errors in the action dictionary of the 'astOfExpression' operation:
- 'EndOfIdentifiers_regular' is not a valid semantic action for 'Tact'
- 'EndOfIdentifiers_ignoreUnspecifiedFields' is not a valid semantic action for 'Tact'
    at Grammar._checkTopDownActionDict (/home/b4cksl4sh/tact/node_modules/ohm-js/dist/ohm.cjs:4477:21)
    at Operation.checkActionDict (/home/b4cksl4sh/tact/node_modules/ohm-js/dist/ohm.cjs:4282:13)
    at Semantics.addOperationOrAttribute (/home/b4cksl4sh/tact/node_modules/ohm-js/dist/ohm.cjs:3996:11)
    at proxy.addOperation (/home/b4cksl4sh/tact/node_modules/ohm-js/dist/ohm.cjs:4200:7)
    at Object.<anonymous> (/home/b4cksl4sh/tact/dist/grammar/grammar.js:779:11)
    at Module._compile (node:internal/modules/cjs/loader:1572:14)
    at Object..js (node:internal/modules/cjs/loader:1709:10)
    at Module.load (node:internal/modules/cjs/loader:1315:32)
    at Function._load (node:internal/modules/cjs/loader:1125:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14) {
  problems: [
    "'EndOfIdentifiers_regular' is not a valid semantic action for 'Tact'",
    "'EndOfIdentifiers_ignoreUnspecifiedFields' is not a valid semantic action for 'Tact'"
  ]
}
```

**Comment by verytactical** [comment]
@Shvandre Today `release-it` was removed from dependencies. Could you please check that this is an issue yet, and close it if it's not?

**Comment by Shvandre** [comment]
@verytactical Looks like it works for me. Node js v23.6.1, arm, macOS
