### ISSUE TITLE
Missing compiler error: Integer overflow on constant evaluation

### ISSUE THREAD

**Issue by byakuren-hijiri** [tact-lang/tact#189]
There is the following constant expression: `const a: Int = 1 >> -1073741824;`

When evaluating it in compile time the following stack trace appears:

```
💼 Compiling project sample...
Tact compilation failed
RangeError: Maximum BigInt size exceeded
    at reduceInt (/home/bh/Dev/tact/dist/types/resolveConstantValue.js:35:22)
    at resolveConstantValue (/home/bh/Dev/tact/dist/types/resolveConstantValue.js:153:16)
    at buildConstantDescription (/home/bh/Dev/tact/dist/types/resolveDescriptors.js:266:67)
    at resolveDescriptors (/home/bh/Dev/tact/dist/types/resolveDescriptors.js:1047:35)
    at precompile (/home/bh/Dev/tact/dist/pipeline/precompile.js:18:55)
    at build (/home/bh/Dev/tact/dist/pipeline/build.js:56:43)
    at Object.run (/home/bh/Dev/tact/dist/node.js:53:47)
    at /home/bh/Dev/tact/bin/tact:25:20
    at Object.<anonymous> (/home/bh/Dev/tact/bin/tact:30:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
```

Expected: A readable compiler error like: `This constant expression cannot be evaluated due to integer overflow`.

Part of: #183
Found while working on #133

**Comment by spartan124** [comment]
Okay. In essence the compiler error handling needs a facelift
