### ISSUE TITLE
TypeScript wrapper class cannot run in browser

### ISSUE THREAD

**Issue by talkol** [tact-lang/tact#2]
`ton-emulator` dependency is not browser friendly

```ts
await SampleTactContract.fromInit(Address.parse("EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N"));
```

```
Uncaught ReferenceError: __dirname is not defined
    at node_modules/ton-emulator/dist/bindings/EmulatorBindings.js (EmulatorBindings.js:19:30)
    at __require2 (chunk-IPKTAYBB.js?v=530909c9:18:50)
    at node_modules/ton-emulator/dist/emulator/ContractSystem.js (ContractSystem.js:17:28)
    at __require2 (chunk-IPKTAYBB.js?v=530909c9:18:50)
    at node_modules/ton-emulator/dist/index.js (index.js:5:24)
```

**Comment by ex3ndr** [comment]
Fixed in `0.10.0`
