### ISSUE TITLE
macOS in CI generates a type error in @tact-lang/coverage/dist/collector/coverage.js

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#273]
Ubuntu and Windows do not do this and this is not happening on my local macOS installation and neither on @Gusarich's macOS computer. Also, this does not fail CI: it's still green.

```
...
Test Suites: 40 passed, 40 total
Tests:       280 passed, 280 total
Snapshots:   191 passed, 191 total
Time:        402.233 s
Ran all test suites.
TypeError: Cannot read properties of undefined (reading 'kind')
    at collectCoverage (/Users/runner/work/tact/tact/node_modules/@tact-lang/coverage/dist/collector/coverage.js:104:29)
    at Object.completeCoverage (/Users/runner/work/tact/tact/node_modules/@tact-lang/coverage/dist/integration/integrate.js:63:44)
    at module.exports (/Users/runner/work/tact/tact/jest.teardown.js:6:18)
    at /Users/runner/work/tact/tact/node_modules/@jest/core/build/runGlobalHook.js:109:19
    at ScriptTransformer.requireAndTranspileModule (/Users/runner/work/tact/tact/node_modules/@jest/transform/build/ScriptTransformer.js:806:24)
    at runGlobalHook (/Users/runner/work/tact/tact/node_modules/@jest/core/build/runGlobalHook.js:101:9)
    at runJest (/Users/runner/work/tact/tact/node_modules/@jest/core/build/runJest.js:374:5)
    at _run10000 (/Users/runner/work/tact/tact/node_modules/@jest/core/build/cli/index.js:343:7)
    at runCLI (/Users/runner/work/tact/tact/node_modules/@jest/core/build/cli/index.js:198:3)
    at Object.run (/Users/runner/work/tact/tact/node_modules/jest-cli/build/run.js:124:37)
Done in 407.01s.
```

**Comment by anton-trunov** [comment]
This looks to be fixed.
