### ISSUE TITLE
Compilation error with map<Address, Address>

### ISSUE THREAD

**Issue by talkol** [tact-lang/tact#40]
Code:

```
import "@stdlib/deploy";

contract Maps with Deployable {

    ma4: map<Address, Address>;

    init(arg: map<Int, Bool>) {
        // no need to initialize maps if they're empty
    }

    receive("set keys") {
        self.ma4.set(address("UQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqEBI"), myAddress());
    }
}
```

Error:

```
Tact compilation failed
Error: Functions "__tact_dict_set_slice_slice" wasn't rendered
    at WriterContext.render (/Users/talkol/Work/tact-lang/tact-by-example/node_modules/@tact-lang/compiler/dist/generator/Writer.js:50:19)
    at writeProgram (/Users/talkol/Work/tact-lang/tact-by-example/node_modules/@tact-lang/compiler/dist/generator/writeProgram.js:345:26)
    at async compile (/Users/talkol/Work/tact-lang/tact-by-example/node_modules/@tact-lang/compiler/dist/pipeline/compile.js:8:18)
    at async build (/Users/talkol/Work/tact-lang/tact-by-example/node_modules/@tact-lang/compiler/dist/pipeline/build.js:72:23)
    at async Object.run (/Users/talkol/Work/tact-lang/tact-by-example/node_modules/@tact-lang/compiler/dist/node.js:53:21)
    at async /Users/talkol/Work/tact-lang/tact-by-example/node_modules/@tact-lang/compiler/bin/tact:18:9
```

**Comment by ex3ndr** [comment]
Fixed in `1.1.0-beta.8`
