### ISSUE TITLE
Missing name information for error message on duplicate definitions from traits

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#498]
```
trait Foo {
    receive("comment") { }
}

trait Bar {
    receive("comment") { }
}

contract Test with Foo, Bar { }
```

compilation fails (as it should) with the following (incorrect) error message:

```
Error: test.tact:11:1: Receive function for "[object Object]" already exists
Line 11, col 1:
  10 | 
> 11 | contract Test with Foo, Bar { }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  12 | 

    at throwCompilationError (/Users/anton_1/ton/tact/dist/errors.js:64:11)
    at copyTraits (/Users/anton_1/ton/tact/dist/types/resolveDescriptors.js:1010:56)
    at processType (/Users/anton_1/ton/tact/dist/types/resolveDescriptors.js:1043:9)
    at processType (/Users/anton_1/ton/tact/dist/types/resolveDescriptors.js:1040:13)
    at processType (/Users/anton_1/ton/tact/dist/types/resolveDescriptors.js:1040:13)
    at resolveDescriptors (/Users/anton_1/ton/tact/dist/types/resolveDescriptors.js:1049:9)
    at precompile (/Users/anton_1/ton/tact/dist/pipeline/precompile.js:18:55)
    at build (/Users/anton_1/ton/tact/dist/pipeline/build.js:58:43)
    at Object.run (/Users/anton_1/ton/tact/dist/node.js:84:47)
```

the `copyTraits` function should not use `f.selector` for error reporting.

**Comment by novusnota** [comment]
Also, should we introduce `virtual` or `abstract` receivers to override them later via `override`? Or just having them in traits is fine as is?

**Comment by anton-trunov** [comment]
hard to say now, should have a use-case first
