### ISSUE TITLE
Strange behavior of `initOf` in contract `init`

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#511]
If I uncomment the commented out line in `receive(_: Foo)`, the tests work as expected and the child contract gets deployed. Otherwise, the tests fail with exit code 135: `Code of a contract was not found`.

## `contracts/test_init.tact`

```tact
import "@stdlib/deploy";

message(42) Foo { }

contract TestNested with Deployable {
  init() { dump("Nested----init@SUCCESS") }
}

contract TestInit with Deployable {
  init() {
    try{
      let init: StateInit = initOf TestNested();
      dump("init@TestInit-1");
      send(SendParameters{
        to: contractAddress(init),
        value: 0,
        mode: SendIgnoreErrors | SendRemainingValue, // don't stop in case of errors
        code: init.code,
        data: init.data,
        body: Deploy { queryId: 0 }.toCell(),
      });
      dump("init@TestInit-SUCCESS");
    } catch (e) {
      dump("ERROR@TestInit");
      dump(e);
    }
  }

  receive(_: Foo) {
//      initOf TestNested();   <-- if commented out `ERROR@TestInit` is observed in the logs
  }
}
```

## `tests/TestInit.spec.ts`

```typescript
import { Blockchain, SandboxContract, TreasuryContract } from '@ton/sandbox';
import { toNano } from '@ton/core';
import { TestInit } from '../wrappers/TestInit';
import '@ton/test-utils';

describe('TestInit', () => {
    let blockchain: Blockchain;
    let deployer: SandboxContract<TreasuryContract>;
    let testInit: SandboxContract<TestInit>;

    beforeEach(async () => {
        blockchain = await Blockchain.create();

        testInit = blockchain.openContract(await TestInit.fromInit());

        deployer = await blockchain.treasury('deployer');

        const deployResult = await testInit.send(
            deployer.getSender(),
            {
                value: toNano('0.5'),
            },
            {
                $$type: 'Deploy',
                queryId: 0n,
            }
        );

        expect(deployResult.transactions).toHaveTransaction({
            from: deployer.address,
            to: testInit.address,
            deploy: true,
            success: true,
        });
    });
    it("should deploy", async () => { });
});
```

### Commented out line

```shell
> TestInit@0.0.1 test
> jest --verbose

  console.log
    #DEBUG#: [DEBUG] File contracts/test_init.tact:26:7
    #DEBUG#: ERROR@TestInit
    #DEBUG#: [DEBUG] File contracts/test_init.tact:27:7
    #DEBUG#: 135

      at SmartContract.runCommon (node_modules/@ton/sandbox/dist/blockchain/SmartContract.js:221:21)

 PASS  tests/TestInit.spec.ts
  TestInit
    ✓ should deploy (202 ms)
```

### Uncommented line

```shell
> TestInit@0.0.1 test
> jest --verbose

  console.log
    #DEBUG#: [DEBUG] File contracts/test_init.tact:13:7
    #DEBUG#: init@TestInit-1
    #DEBUG#: [DEBUG] File contracts/test_init.tact:23:7
    #DEBUG#: init@TestInit-SUCCESS

      at SmartContract.runCommon (node_modules/@ton/sandbox/dist/blockchain/SmartContract.js:221:21)

  console.log
    #DEBUG#: [DEBUG] File contracts/test_init.tact:6:12
    #DEBUG#: Nested----init@SUCCESS

      at SmartContract.runCommon (node_modules/@ton/sandbox/dist/blockchain/SmartContract.js:221:21)

 PASS  tests/TestInit.spec.ts
  TestInit
    ✓ should deploy (205 ms)
```

## FunC and Fift code diff between the code with commented out line and uncommented line

```shell
$ diffoscope --exclude-directory-metadata=yes build-no-initof-in-rcv build-with-initof-in-rc

│ │  ((tuple), ()) $TestInit$_internal_binary_Foo(tuple $self, tuple $_) impure inline {
│ │      var $self = $self;
│ │      var $_ = $_;
│ │ +    $TestNested$_init_child(__tact_context_sys);
│ │      return ($self, ());
│ │  }
│ │  
...
│ │    $TestInit$_internal_binary_Foo PROCINLINE:<{
│ │      DROP
│ │ +    __tact_context_sys GETGLOB
│ │ +    $TestNested$_init_child INLINECALLDICT
│ │ +    2DROP
│ │    }>
...

...
```

**Comment by anton-trunov** [comment]
#367 might be related here
