### ISSUE TITLE
Imports leak from a file to its imports

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#743]
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Relevant Tact/build system log output

```shell
❯ tact master.tact
💼 Compiling project master ...
   > User: tact compiler
   > User: func compiler
   > Master: tact compiler
   > Master: func compiler
   > Packaging
   > User
   > Master
   > Bindings
   > User
   > Master
   > Reports
   > User
   > Master
```

### What happened?

Compilation succeeds for the `user.tact` file (see below) which fails to import a trait from a separate file.

### What did you expect?

Compilation should fail for `user.tact`.

### Steps to reproduce

Consider the following three files:

```tact
/// file: master.tact

import "./trait";
import "./user";

contract Master { }
```

```tact
/// file: user.tact

// note that user.tact does not import ./trait.tact
contract User with TestTrait { }
```

```tact
/// file: trait.tact

trait TestTrait { }
```

### How do you run Tact?

Tact CLI

### Anything else?

Incidentally, if I try to compile `user.tact`, compilation fails, as expected:

```shell
❯ tact user.tact
💼 Compiling project user ...
Tact compilation failed
Error: user.tact:2:1: Trait TestTrait not found
Line 2, col 1:
  1 | // user does not import ./trait.tact
> 2 | contract User with TestTrait { }
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  3 | 

    at throwCompilationError (/Users/anton_1/ton/tact/dist/errors.js:77:11)
    at visit (/Users/anton_1/ton/tact/dist/types/resolveDescriptors.js:894:56)
    at resolveDescriptors (/Users/anton_1/ton/tact/dist/types/resolveDescriptors.js:912:17)
    at precompile (/Users/anton_1/ton/tact/dist/pipeline/precompile.js:18:55)
    at build (/Users/anton_1/ton/tact/dist/pipeline/build.js:62:43)
    at Object.run (/Users/anton_1/ton/tact/dist/node.js:100:47)
```

**Comment by anton-trunov** [comment]
There are users who rely on this behavior already, so we need to document Tact automatically re-exports imported things.
