### ISSUE TITLE
Tact failes to resolve expression with TypeError

### ISSUE THREAD

**Issue by imartemy1524** [tact-lang/tact#744]
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Tact source code

```tact
const JSON_TYPE_OBJECT: Int = 0;
const JSON_TYPE_ARRAY: Int = 1;
const JSON_TYPE_STRING: Int = 2;
const JSON_TYPE_NUMBER: Int = 3;
const JSON_TYPE_COINS: Int = 4;

struct ObjectElement{
    key: String;
    value: JsonElement;
}

struct JsonBuilderObject{
    //slice - String
    content: map<Int as uint8, ObjectElement>;
    elementsCount: Int as uint64 = 0;
}
struct JsonBuilderArray{
    //slice - String
    content: map<Int as uint8, JsonElement>;
    elementsCount: Int as uint64 = 0;
}

struct JsonElement{
    type: Int as uint8;
    value: Slice;
}


fun createJsonArray(): JsonElement{
    //TODO: toCell costs a lot of gas
    return JsonElement{type: JSON_TYPE_ARRAY, value: JsonBuilderArray{content: emptyMap()}.toCell().asSlice()};
}
fun createJsonObject(): JsonElement{
    return JsonElement{type: JSON_TYPE_OBJECT, value: JsonBuilderObject{content: emptyMap()}.toCell().asSlice()};
}
fun creteJsonString(value: String): JsonElement{
    return JsonElement{type: JSON_TYPE_STRING, value: value.asSlice()};
}
fun createJsonNumber(value: Int): JsonElement{
    return JsonElement{type: JSON_TYPE_NUMBER, value: beginCell().storeInt(value, 64).endCell().asSlice()};
}
fun createJsonCoins(value: Int): JsonElement{
    return JsonElement{type: JSON_TYPE_COINS, value: beginCell().storeCoins(value).endCell().asSlice()};
}

extends fun toString(self: JsonElement): String {
    if(self.type == JSON_TYPE_STRING){
        //TODO: quote escaping
        return beginString().concat("\"").concat(self.value.asString()).concat("\"").toString();
    }
    else if(self.type == JSON_TYPE_COINS){
        let coins = self.value.loadCoins();
        return coins.toCoinsString();
    }
    else if(self.type == JSON_TYPE_NUMBER){
        return self.value.loadInt(64).toString();
    }
    else if(self.type == JSON_TYPE_OBJECT){
        let builder: StringBuilder = beginString();
        builder.append("{");
        let object: JsonBuilderObject = JsonBuilderObject.fromSlice(self.value);
        foreach(key, value in object.content){
            builder.append("\"");
            builder.append(value.key);
            builder.append("\":");
            builder.append((value.value).toString());
            if(key < object.elementsCount - 1){
                builder.append(",");
            }
        }
        builder.append("}");
        return builder.toString();
    }
    else if(self.type == JSON_TYPE_ARRAY){
        let builder: StringBuilder = beginString();
        builder.append("[");
        let array: JsonBuilderArray = JsonBuilderArray.fromSlice(self.value);
        foreach(key, value in array.content){
            builder.append(toString(value));
            if(key < array.elementsCount - 1){
                builder.append(",");
            }
        }
        builder.append("]");
        return builder.toString();
    }
}
extends fun appendToArray(self: JsonElement, value: JsonElement): JsonElement {
    require(value.type == JSON_TYPE_ARRAY, "Invalid JSON object type");
    let element: JsonBuilderArray = JsonBuilderArray.fromSlice(value.value);
    element.content.set(element.elementsCount, value);
    element.elementsCount += 1;
    return JsonElement{type: JSON_TYPE_ARRAY, value: element.toCell().asSlice()};
}
extends fun appendToObject(self: JsonElement, key: String, value: JsonElement): JsonElement {
    require(value.type == JSON_TYPE_OBJECT, "Invalid JSON object type");
    let element: JsonBuilderObject = JsonBuilderObject.fromSlice(value.value);
    element.content.set(element.elementsCount, ObjectElement{key, value});
    element.elementsCount += 1;
    return JsonElement{type: JSON_TYPE_OBJECT, value: element.toCell().asSlice()};
}
```

### Relevant Tact/build system log output

```shell
(Use `node --trace-deprecation ...` to show where the warning was created)
Using file: JsonBuilder
Build script running, compiling JsonBuilder
⏳ Compiling...Tact compilation failed
TypeError: Cannot read properties of undefined (reading 'length')
    at resolveStaticCall (.../JsonBuilder/node_modules/@tact-lang/compiler/dist/types/resolveExpression.js:312:18)
    at resolveExpression (.../JsonBuilder/node_modules/@tact-lang/compiler/dist/types/resolveExpression.js:512:20)
    at resolveCall (.../JsonBuilder/node_modules/@tact-lang/compiler/dist/types/resolveExpression.js:336:15)
    at resolveExpression (.../JsonBuilder/node_modules/@tact-lang/compiler/dist/types/resolveExpression.js:515:20)
    at processStatements (.../JsonBuilder/node_modules/@tact-lang/compiler/dist/types/resolveStatements.js:245:69)
    at processStatements (.../JsonBuilder/node_modules/@tact-lang/compiler/dist/types/resolveStatements.js:423:27)
    at processCondition (.../JsonBuilder/node_modules/@tact-lang/compiler/dist/types/resolveStatements.js:73:19)
    at processCondition (.../JsonBuilder/node_modules/@tact-lang/compiler/dist/types/resolveStatements.js:96:19)
    at processCondition (.../JsonBuilder/node_modules/@tact-lang/compiler/dist/types/resolveStatements.js:96:19)
    at processCondition (.../JsonBuilder/node_modules/@tact-lang/compiler/dist/types/resolveStatements.js:96:19)
Error: Could not find boc in tact compilation result
```

### What happened?

Tact couldn't compile my code. It don't throw any error, instead, compiler just fails to build the code.

### What did you expect?

I expect to see exact error why the compilation failed.

### Steps to reproduce

Here is a link with my tact repository with code: https://github.com/imartemy1524/TactJsonBuilder

Shell script to download/build:
```shell
git clone https://github.com/imartemy1524/TactJsonBuilder -b tact-error
cd TactJsonBuilder/
npm i
npx blueprint build

```

### How do you run Tact?

Blueprint

### Anything else?

As I understood, this exceptions throws which compiler checks the code (`npx tact --check ./contracts/json.tact` also throws this error)
Maybe tact is just scared of the things I'm trying to do, it's not prepared for this :)

**Comment by anton-trunov** [comment]
Thanks for the report! Your contracts are the most sophisticated ones I've seen so far. (Btw, in what follows I'm not questioning your design decision to do string manipulations on-chain)

The problem is `toString(value)` called as a static function instead of using the extension function call syntax `value.toString()`.

Incidentally, Tact will not understand if your function always return a string or not. But the `return`-analysis cannot know it for sure (until we introduce algebraic datatypes and exhaustive pattern matching into the language).
