### ISSUE TITLE
Internal compiler error when comparing if map is empty using `emptyMap` function

### ISSUE THREAD

**Issue by jeshecdom** [tact-lang/tact#808]
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Tact source code

```tact
fun test(): Bool {
   let s: map<Int,Int> = emptyMap();
   return s == emptyMap();
}

contract TestContract {
}
```

### Relevant Tact/build system log output

```shell
Tact compilation failed
Error: (Internal Compiler Error) Invalid types for binary operation: /home/jesus/tact/tact/bin/test.tact:3:15
    at writeExpression (/home/jesus/tact/tact/dist/generator/writers/writeExpression.js:278:19)
    at writeCastedExpression (/home/jesus/tact/tact/dist/generator/writers/writeFunction.js:25:77)
    at writeStatement (/home/jesus/tact/tact/dist/generator/writers/writeFunction.js:56:32)
    at /home/jesus/tact/tact/dist/generator/writers/writeFunction.js:475:25
    at WriterContext.body (/home/jesus/tact/tact/dist/generator/Writer.js:188:9)
    at /home/jesus/tact/tact/dist/generator/writers/writeFunction.js:463:21
    at WriterContext.fun (/home/jesus/tact/tact/dist/generator/Writer.js:141:9)
    at writeFunction (/home/jesus/tact/tact/dist/generator/writers/writeFunction.js:454:17)
    at /home/jesus/tact/tact/dist/generator/writeProgram.js:277:43
    at Array.forEach (<anonymous>)
```

### What happened?

Checking if the map is empty using the `emptyMap` function, produces the error. But note that if we remove the contract declaration, like this:
```
fun test(): Bool {
   let s: map<Int,Int> = emptyMap();
   return s == emptyMap();
}
```
the error disappears. 

Also, if we compare against `null`, the error disappears:
```
fun test(): Bool {
   let s: map<Int,Int> = emptyMap();
   return s == null;
}

contract TestContract {
}
```

### What did you expect?

To compile without errors. Is this probably caused by the compiler not able to determine the type of `emptyMap()`?

### How do you run Tact?

Tact CLI

**Comment by anton-trunov** [comment]
```
return s == null;
```

works because the compiler is too smart now -- it sees the comparison is always true at compile time and the code generator does not actually deal with map comparisons
