### ISSUE TITLE
Build error: TypeError: `paramSet.isSubsetOf` is not a function

### ISSUE THREAD

**Issue by A1tura** [tact-lang/tact#840]
I get that error 
```
💼 Compiling project main ...
Tact compilation failed
TypeError: paramSet.isSubsetOf is not a function
    at resolveFunctionDescriptor (/usr/local/lib/node_modules/@tact-lang/compiler/dist/types/resolveDescriptors.js:600:31)
    at resolveDescriptors (/usr/local/lib/node_modules/@tact-lang/compiler/dist/types/resolveDescriptors.js:1243:19)
    at precompile (/usr/local/lib/node_modules/@tact-lang/compiler/dist/pipeline/precompile.js:18:55)
    at build (/usr/local/lib/node_modules/@tact-lang/compiler/dist/pipeline/build.js:62:43)
    at Object.run (/usr/local/lib/node_modules/@tact-lang/compiler/dist/node.js:101:47)
```
When I try to build my smart contract

**Comment by jubnzv** [comment]
Please update Node.js to version 22.

If you use `nvm`, you can do it this way: `nvm install v22.8.0 && nvm alias default v22.8.0`.
