### ISSUE TITLE
Tact compilation error: paramSet.isSubsetOf is not a function

### ISSUE THREAD

**Issue by nordost8** [tact-lang/tact#919]
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Tact source code

```tact
Choose the project template 
An empty contract (TACT)
```

### Relevant Tact/build system log output

```shell
nordost@nordost-pc:~/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract$ npm create ton@latest

? Project name Wager
? First created contract name (PascalCase) WagerContract
? Choose the project template An empty contract (TACT)

[1/3] Copying files...
[2/3] Installing dependencies...

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@tact-lang/compiler@1.5.2',
npm WARN EBADENGINE   required: { node: '>=22.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '9.6.7' }
npm WARN EBADENGINE }
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 441 packages, and audited 442 packages in 16s

50 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[3/3] Creating your first contract...
Build script running, compiling WagerContract
⏳ Compiling...Tact compilation failed
TypeError: paramSet.isSubsetOf is not a function
    at resolveFunctionDescriptor (/home/nordost/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract/Wager/node_modules/@tact-lang/compiler/dist/types/resolveDescriptors.js:600:31)
    at resolveDescriptors (/home/nordost/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract/Wager/node_modules/@tact-lang/compiler/dist/types/resolveDescriptors.js:1243:19)
    at precompile (/home/nordost/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract/Wager/node_modules/@tact-lang/compiler/dist/pipeline/precompile.js:18:55)
    at Object.build (/home/nordost/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract/Wager/node_modules/@tact-lang/compiler/dist/pipeline/build.js:62:43)
    at doCompileTact (/home/nordost/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract/Wager/node_modules/@ton/blueprint/dist/compile/compile.js:113:28)
    at doCompileInner (/home/nordost/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract/Wager/node_modules/@ton/blueprint/dist/compile/compile.js:127:22)
    at doCompile (/home/nordost/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract/Wager/node_modules/@ton/blueprint/dist/compile/compile.js:142:23)
    at async buildOne (/home/nordost/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract/Wager/node_modules/@ton/blueprint/dist/build.js:21:24)
    at async create (/home/nordost/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract/Wager/node_modules/@ton/blueprint/dist/cli/create.js:102:9)
    at async main (/home/nordost/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract/Wager/node_modules/@ton/blueprint/dist/cli/cli.js:91:5)
Error: Could not find boc in tact compilation result

Error: Command failed: npm exec blueprint -- create WagerContract --type tact-empty
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at main (/home/nordost/.npm/_npx/b56225140edd990c/node_modules/create-ton/dist/cli.js:133:34) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 24839,
  stdout: null,
  stderr: null
}
```

### What did you expect?

Successful compilation

### Steps to reproduce

nordost@nordost-pc:~/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract$ npm create ton@latest

? Project name Wager
? First created contract name (PascalCase) WagerContract
? Choose the project template An empty contract (TACT)

### Anything else?

Here’s a list of the commands I have already tried:

Uninstall and reinstall Tact:
npm uninstall @tact-lang/compiler
npm install @tact-lang/compiler

Clear npm cache:
npm cache clean --force
Reinstall all dependencies (including deleting the node_modules folder):

rm -rf node_modules package-lock.json
npm install

nordost@nordost-pc:~/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract$ npx tact --version
1.5.2
git commit: 1fadc812ebcef732727d40b4d24e9059a316a780
nordost@nordost-pc:~/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
nordost@nordost-pc:~/Projects/WagerBackendRepo/telegram-web-app-backend-deploy/contract$ node -v
v18.17.1

**Comment by anton-trunov** [comment]
As the error message says, use `node` version 22
